language: php

php:
  - 5.3

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - mkdir tests/files
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - bin/phpunit
  - bin/phpunit --coverage-text --coverage-clover coverage.xml
  - bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
